### ISSUE TITLE
Custome storage in chat framework in node js

### ISSUE THREAD

**Issue by aakashkag** [ankitbko/Microsoft.Bot.Builder.RedisStore#2]
how we can do same in node js. I am not able to find any example in node js.

**Comment by ankitbko** [comment]
I have not gone through in details the Node library. But you may try implementing `IBotStorage` similar to how I have done. You can see an example [here](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/storage/BotStorage.ts).

**Comment by aakashkag** [comment]
Thanks! 
I open ticket [https://github.com/Microsoft/BotBuilder/issues/1943]

**Comment by aakashkag** [comment]
Finally i written code to store session data into Mongo db using node js 
[Code with description ](https://github.com/aakashkag/BotBuilder-MongoDB/)
